name: Build and Push jembi/mpi-mediator image

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v3
      - run: npm run build
      - run: docker build -t jembi/mpi-mediator:${{ github.ref_name }} .
      - run: docker push jembi/mpi-mediator:${{ github.ref_name }}
