name: Scan latest mpi image

on: push

jobs:
  scan-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Run trivy vulnerability scanner for the MPI - mediator image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: jembi/mpi-mediator:latest
          format: 'sarif'
          output: 'trivy-results.sarif'
        
      - name: Upload Trivy scan results to Github Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
